apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: xam-messenger
type: Opaque
stringData:
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
  endpoint: "http://minio.xam-messenger.svc.cluster.local:9000"