apiVersion: v1
kind: Secret
metadata:
  name: csi-s3-secret
  namespace: kube-system
type: Opaque
stringData:
  accessKeyID: "minioadmin"
  secretAccessKey: "minioadmin"
  endpoint: "http://10.111.187.34:9000"
  region: "us-east-1"