apiVersion: batch/v1
kind: Job
metadata:
  name: migrate-users
spec:
  backoffLimit: 3
  template:
    spec:
      initContainers:
        - name: wait-for-postgres
          image: postgres:16-alpine
          command:
            - sh
            - -c
            - until pg_isready -h postgres -U $(POSTGRES_USER); do echo waiting for postgres; sleep 2; done
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: messager-db-secret
                  key: POSTGRES_USER
      restartPolicy: Never
      containers:
        - name: migrate-users
          image: ghcr.io/kukymbr/goose-docker:latest
          env:
            - name: GOOSE_DRIVER
              value: postgres
            - name: GOOSE_DBSTRING
              valueFrom:
                secretKeyRef:
                  name: messager-db-secret
                  key: USER_DB_DSN
            - name: GOOSE_MIGRATION_DIR
              value: /migrations
          volumeMounts:
            - name: migrations
              mountPath: /migrations
      volumes:
        - name: migrations
          configMap:
            name: users-migrations-cm